spring:
  output:
    ansi:
      enabled: always # ?? ?? ??

  application:
    name: springboot_test

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ????


server:
  port: 8080